version: '3'
services:

  # Server
  backend-service:
    container_name: backend-service
    build:
      context: .
      dockerfile: dev.Dockerfile
    command: 'npm run watch-debug'
    ports:
      - '3000:3000'
      - '9229:9229'
    volumes:
      - ./:/app
      - '/app/node_modules'
